# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/src;/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/build_simulator")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/build_simulator/postinst;")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "argos3_simulator (>= 3.0.0)")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "ARGoS-KheperaIV (KheperaIV plugin for ARGoS)
 A plugin to support the KheperaIV robot (https://www.k-team.com/khepera-iv/)
 into the ARGoS multi-robot simulator (http://www.argos-sim.info/).")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "http://github.com/ilpincy/argos3-kheperaiv/")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Carlo Pinciroli <ilpincy@gmail.com>")
set(CPACK_DEBIAN_PACKAGE_SECTION "contrib/science")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/build_simulator;argos3_;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr")
set(CPACK_MODULE_PATH "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/src/cmake;/usr/share/argos3/cmake")
set(CPACK_NSIS_DISPLAY_NAME "argos3plugins_simulator_kheperaiv ..")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "argos3plugins_simulator_kheperaiv ..")
set(CPACK_OUTPUT_CONFIG_FILE "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/build_simulator/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "ARGoS-KheperaIV (KheperaIV plugin for ARGoS)
 A plugin to support the KheperaIV robot (https://www.k-team.com/khepera-iv/)
 into the ARGoS multi-robot simulator (http://www.argos-sim.info/).")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "KheperaIV support for ARGoS3")
set(CPACK_PACKAGE_FILE_NAME "argos3plugins_simulator_kheperaiv-..-x86_64-")
set(CPACK_PACKAGE_HOMEPAGE "http://github.com/ilpincy/argos3-kheperaiv/")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "argos3plugins_simulator_kheperaiv ..")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "argos3plugins_simulator_kheperaiv ..")
set(CPACK_PACKAGE_MAINTAINER "Carlo Pinciroli <ilpincy@gmail.com>")
set(CPACK_PACKAGE_NAME "argos3plugins_simulator_kheperaiv")
set(CPACK_PACKAGE_RELEASE "")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "..")
set(CPACK_PACKAGE_VERSION_MAJOR "")
set(CPACK_PACKAGE_VERSION_MINOR "")
set(CPACK_PACKAGE_VERSION_PATCH "")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_RESOURCE_FILE_LICENSE "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/src/../doc/ARGoS_LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/src/../README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.16/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_DESCRIPTION "ARGoS-KheperaIV (KheperaIV plugin for ARGoS)
 A plugin to support the KheperaIV robot (https://www.k-team.com/khepera-iv/)
 into the ARGoS multi-robot simulator (http://www.argos-sim.info/).")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_REQUIRES "argos3_simulator >= 3.0.0")
set(CPACK_RPM_PACKAGE_URL "http://github.com/ilpincy/argos3-kheperaiv/")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/build_simulator/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "ON")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/midnightpegasus/Documents/WPI/MQP/Pinci_Send/argos3-kheperaiv-gripper-module/build_simulator/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
